# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190625_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
    ]
