# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190626_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='is_activated',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='activated',
            field=models.IntegerField(choices=[(0, '未激活'), (1, '已激活')], default=0, verbose_name='是否激活'),
        ),
    ]
